###
GET http://localhost:9999/getCards HTTP/1.1
Content-Type: application/json

{
  "id": 432425
}

###
PUT http://localhost:9999/editCard HTTP/1.1

###
DELETE http://localhost:9999/removeCard HTTP/1.1

###
POST http://localhost:9999/getCards HTTP/1.1

###
POST http://localhost:9999/request?key=queryValue1&key=queryValue2 HTTP/1.1
Accept: text/plain
Content-Type: application/x-www-form-urlencoded

key=postFormValue1&key=postFormValue2
###
POST http://localhost:9999/addCard HTTP/1.1
Content-Type: application/json

{
  "id": 432425,
  "issuer":"VISA",
  "name_card":"New Virtual Card",
  "type":"Virtual"
}


